# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-classifier
  namespace: text-classifier
  labels:
    app: text-classifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text-classifier
  template:
    metadata:
      labels:
        app: text-classifier
    spec:
      containers:
        - name: text-classifier
          image: text-classifier/text-classifier:${VERSION}
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "500Mi" # TODO: Once the pod is running validate the memory usage
              cpu: "400m"
            limits:
              memory: "2Gi" # TODO: Once the pod is running validate the memory usage
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: text-classifier-hpa
  namespace: text-classifier
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: text-classifier
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80 # 80% CPU utilization
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80 # 75% memory utilization