# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: text-classifier-service
  namespace: text-classifier
spec:
  selector:
    app: text-classifier
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
